---
abstract: 'Perl module to control SCSI devices'
author:
  - 'Peter Corlett <abuse@cabal.org.uk>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-SCSI
requires:
  Carp: 0
  Fcntl: 0
  Module::Load: 0
  fields: 0
  perl: 5.009004
version: 1.004
